config/routes.rb
Rails.application.routes.draw do
  resources :weather_locations
  resources :weather_grids
  devise_for :users, controllers: { registrations: "registrations" , sessions: "sessions"}

resources :weather_grid

get '/subscriptions/cancel_subscription'  => 'subscriptions#cancel_subscription'
get '/subscriptions/update_card'          => 'subscriptions#update_card'
post '/subscriptions/update_card_details' => 'subscriptions#update_card_details'

resources :subscriptions

root to: "home#index"

mount StripeEvent::Engine, at: '/stripe-event' # provide a custom path

end

app/models/weather_grid.rb
class WeatherGrid < ActiveRecord::Base
  belongs_to :user
  has_many :weather_locations, dependent: :destroy
end

app/controllers/weather_grid_controller.rb
class WeatherGridController < ApplicationController

  # devise helper
  before_action :authenticate_user!

  def index

  end
end

app/controllers/weather_grids_controller.rb
class WeatherGridsController < ApplicationController
  require 'forecast_io'
  require 'plan_manager'
  include  PlanManager
  before_action :set_weather_grid, only: [:show, :edit, :update, :destroy]

  # Helper method provided by cancan
  load_and_authorize_resource param_method: :weather_grid_params

  # Authentication
  before_action :authenticate_user!

  # GET /weather_grids
  # GET /weather_grids.json
  def index
    # @weather_grids = WeatherGrid.all
  end

  # GET /weather_grids/1
  # GET /weather_grids/1.json
  def show
    @weather_locations = WeatherLocation.where(weather_grid: @weather_grid)
    @weather_info = []

    for w in @weather_locations
      data = Hash.new
      data['location'] = w
      data['weather'] = get_weather(w)
      @weather_info.push(data)
    end

  end

  # GET /weather_grids/new
  def new

   # @weather_grid = WeatherGrid.new
  end

  # GET /weather_grids/1/edit
  def edit
  end

  # POST /weather_grids
  # POST /weather_grids.json
  def create

  #  @weather_grid = WeatherGrid.new(weather_grid_params)

    errors = plan_check("create", "weather_grid")

    unless errors.nil?
      flash[:notice] = errors
      redirect_to action: :new
      return
    end

    @weather_grid.user = current_user

    respond_to do |format|
      if @weather_grid.save
        format.html { redirect_to @weather_grid, notice: 'Weather grid was successfully created.' }
        format.json { render :show, status: :created, location: @weather_grid }
      else
        format.html { render :new }
        format.json { render json: @weather_grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weather_grids/1
  # PATCH/PUT /weather_grids/1.json
  def update
    respond_to do |format|
      if @weather_grid.update(weather_grid_params)
        format.html { redirect_to @weather_grid, notice: 'Weather grid was successfully updated.' }
        format.json { render :show, status: :ok, location: @weather_grid }
      else
        format.html { render :edit }
        format.json { render json: @weather_grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weather_grids/1
  # DELETE /weather_grids/1.json
  def destroy
    @weather_grid.destroy
    respond_to do |format|
      format.html { redirect_to weather_grids_url, notice: 'Weather grid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def get_weather(weather_location)
      forecast_api_key = "c569f6a466fe145dbdfcd7775d01d04d"
      ForecastIO.api_key = forecast_api_key

      forecast = ForecastIO.forecast(weather_location.latitude, weather_location.longitude, params: { units: 'si' })

      return forecast

    end

    # Use callbacks to share common setup or constraints between actions.
    def set_weather_grid
      @weather_grid = WeatherGrid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weather_grid_params
      params.require(:weather_grid).permit(:name, :user_id)
    end
end

app/helpers/weather_grid_helper.rb
module WeatherGridHelper
end

app/helpers/weather_grids_helper.rb
module WeatherGridsHelper
  def forecast_to_css_mapping(forecast_icon)
      forecast_to_css_mapping = Hash.new
      forecast_to_css_mapping['clear-day']           = 'climacon sun'
      forecast_to_css_mapping['clear-night']         = 'climacon moon'
      forecast_to_css_mapping['rain']                = 'climacon rain'
      forecast_to_css_mapping['snow']                = 'climacon snow'
      forecast_to_css_mapping['sleet']               = ''
      forecast_to_css_mapping['wind']                = 'climacon wind'
      forecast_to_css_mapping['fog']                 = 'climacon fog'
      forecast_to_css_mapping['cloudy']              = 'climacon cloud'
      forecast_to_css_mapping['partly-cloudy-day']   = 'climacon cloud sun'
      forecast_to_css_mapping['partly-cloudy-night'] = 'climacon cloud moon'

      return forecast_to_css_mapping[forecast_icon]
  end
end

app/views/weather_grids/_form.html.erb
<%= simple_form_for(@weather_grid) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>

    <% #<%= f.association :user %>

    <%= f.input :user, as: :hidden, input_html: {value: current_user.id, readonly: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/weather_grids/edit.html.erb
<h1>Editing Weather Grid</h1>

<%= render 'form' %>

<%= link_to 'Show', @weather_grid %> |
<%= link_to 'Back', weather_grids_path %>

app/views/weather_grids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Weather Grids</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weather_grids.each do |weather_grid| %>
      <tr>
        <td><%= weather_grid.name %></td>
        <td><%= weather_grid.user.email %></td>

        <% if can? :read, WeatherGrid %>
          <td><%= link_to 'Show', weather_grid %></td>
        <% end %>

        <% if can? :update, weather_grid %>
          <td><%= link_to 'Edit', edit_weather_grid_path(weather_grid) %></td>
        <% end %>

        <% if can? :delete, weather_grid  %>
          <td><%= link_to 'Destroy', weather_grid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather grid', new_weather_grid_path %>

app/views/weather_grids/new.html.erb
<h1>New Weather Grid</h1>

<%= render 'form' %>

<%= link_to 'Back', weather_grids_path %>

app/views/weather_grids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @weather_grid.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @weather_grid.user %>
</p>

<%= link_to 'Edit', edit_weather_grid_path(@weather_grid) %> |
<%= link_to 'Back', weather_grids_path %>

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><%= @weather_grid.name %></h3>
        </div>
        <br>


        <%# Show all weather locations here  %>

        <% unless @weather_info.blank? %>
            <% @weather_info.each_with_index do |weather_info, index| %>

                <%# If index is even, then it is a new row  %>

                <% if index % 2 == 0 %>
                    <%# Open the row here  %>
                    <div class="row">
                <% end %>


                    <div class="col-sm-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <%=  weather_info['location'].city %> [<%=  weather_info['location'].latitude %>, <%=  weather_info['location'].longitude %>  ]
                            </div>

                            <% css = forecast_to_css_mapping(weather_info['weather'].currently.icon) %>

                            <div class="row">
                                <div class="col-sm-6 col-sm-offset-3">
                                    <div class="weather_summary">
                                        <h4><%= weather_info['weather'].currently.summary %></h4>
                                    </div>
                                </div>
                                <div class="col-sm-4 col-sm-offset-4">
                                    <div class="weather_icon <%= css %>" >
                                    </div>
                                </div>
                            </div>



                            <div class="row">
                                <div class="col-sm-10">
                                    <%= weather_info['weather'].hourly.summary %>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-10">
                                    <%= weather_info['weather'].daily.summary %>
                                </div>
                            </div>

                        </div>
                    </div>


                 <% if index % 2  != 0 %>
                        <%# Close the row here  %>
                    </div>
                <% end %>

            <% end %>


        <% else %>
            No data to display
        <% end %>

    </div>

</div>