config/routes.rb
Rails.application.routes.draw do
  resources :weather_locations
  resources :weather_grids
  devise_for :users, controllers: { registrations: "registrations" , sessions: "sessions"}

resources :weather_grid

get '/subscriptions/cancel_subscription'  => 'subscriptions#cancel_subscription'
get '/subscriptions/update_card'          => 'subscriptions#update_card'
post '/subscriptions/update_card_details' => 'subscriptions#update_card_details'

resources :subscriptions

root to: "home#index"

mount StripeEvent::Engine, at: '/stripe-event' # provide a custom path

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user

  def new
    @plans = Plan.all
  end

  def index
    @account = Account.find_by_email(current_user.email)
  end

  def edit
    @account = Account.find(params[:id])
    @plans  = Plan.all
  end

  def create
    # ap "Inside create in subscription. See params hash"
    # ap params

    # Get the credit card details submitted by the form
    token           = params[:stripeToken]

    plan            = params[:plan][:stripe_id]

    email           = current_user.email

    current_account = Account.find_by_email(current_user.email)
    customer_id     = current_account.customer_id
    current_plan    = current_account.stripe_plan_id

    if customer_id.nil?
      # New customer, create a new customer
      # Create a Customer
      @customer = Stripe::Customer.create(
        :source => token,
        :plan => plan,
        :email => email
      )

      subscriptions   = @customer.subscriptions
      @subscribed_plan = subscriptions.data.find { |o| o.plan.id == plan }

    else
      # Customer exists
      # Get customer from Stripe
      @customer = Stripe::Customer.retrieve(customer_id)
      @subscribed_plan = create_or_update_subscription(@customer, current_plan, plan)


    end

    # Get current period end - This is a unix timestamp
    current_period_end = @subscribed_plan.current_period_end

    # Convert to datetime
    active_until = Time.at(current_period_end).to_datetime

    save_account_details(current_account, plan, @customer.id, active_until)


    redirect_to :root, :notice => "Succesfully subscribed to plan " + plan

  rescue => e
    redirect_to :back, :flash => { :error => e.message }

  end

  def update_card

  end

  def update_card_details
    token           = params[:stripeToken]

    # Get cust id
    current_account = Account.find_by_email(current_user.email)
    customer_id     = current_account.customer_id

    # Get cust from stripe
    customer = Stripe::Customer.retrieve(customer_id)

    # Set new card token
    customer.source = token
    customer.save

    redirect_to '/subscriptions', notice: "Card updated successfully"

  rescue  => e
    redirect_to '/subscriptions/update_card', :flash => { :notice => e.message }

  end

  def cancel_subscription

    current_account = Account.find_by_email(current_user.email)
    customer_id     = current_account.customer_id
    current_plan    = current_account.stripe_plan_id

    if current_plan.blank?
        raise "No plan found to unsubscribe"
    end

    # Fetch customer from stripe
    customer = Stripe::Customer.retrieve(customer_id)

    # Get current subscription
    subscriptions = customer.subscriptions

    # Find the subscription that we want to cancel
    current_subscribed_plan = subscriptions.data.find { |o| o.plan.id == current_plan }

    if current_subscribed_plan.blank?
      raise "Subscription not found"
    end

    # Delete subscription
    current_subscribed_plan.delete

    # Udpdate account model
    save_account_details(current_account, "", customer_id, Time.at(0).to_datetime)

    @message = "Subscription cancelled successfully"

    rescue => e
      redirect_to "/subscriptions", :flash => { :error => e.message }


  end

  def save_account_details(account, plan, customer_id, active_until)

    # Customer created with a valid subscription
    # So, update account model wit details

    account.stripe_plan_id = plan
    account.customer_id    = customer_id
    account.active_until   = active_until
    account.save!
  end

  def create_or_update_subscription(customer, current_plan, new_plan)
    subscriptions = customer.subscriptions
    # Get current subscription
    current_subscription = subscriptions.data.find { |o| o.plan.id == current_plan }

    if current_subscription.blank?
      # No current subscription
      # Maybe the customer unsubscribed prvlsy or maybe the card was declined
      # So, create a new subscription to existing customer
      subscription = customer.subscriptions.create({:plan => new_plan})
    else
      # Existing subscription found
      # Must be an upgrade or downgrade
      # So update existing subscription with new plan
      current_subscription.plan = new_plan
      subscription = current_subscription.save
    end

    return subscription
  end

  # Auth user or raise exception
  def authorize_user
    authorize! :manage, :subscriptions
  end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_creditcard.html.erb
<%= javascript_include_tag "https://js.stripe.com/v2/" %>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_tag "/subscriptions", id: "payment-form" do %>

      <span class="payment-errors text-danger"></span>

      <%= collection_select :plan, :stripe_id, @plans, :stripe_id, :name, {}, { class: "form-control"} %>

      <div class="form-group">
        <label for="number">Card Number</label>
        <input type="text" size="20" class="form-control" id="number" data-stripe="number"/>
      </div>

      <div class="form-group">
        <label for="cvc">CVC</label>
        <input type="text" size="4" class="form-control" id="cvc" data-stripe="cvc"/>
      </div>

      <label for="exp">Expiration (MM/YYYY)</label>

      <div class="form-group">
        <div>
          <input type="text" size="2" class="form-control exp-field" id="exp" data-stripe="exp-month"/>
          <span> / </span>
          <input type="text" size="4" class="form-control exp-field" data-stripe="exp-year"/>
        </div>
      </div>

      <button type="submit" class="btn btn-primary">Submit Payment</button>
    <% end %>

  </div>
</div>

<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_OQPwSJ6PqwdWCcOnu8EYiVG1');
  // ...
</script>

app/views/subscriptions/_plans.html.erb
<div class="row">
  <div class="col-sm-2 col-sm-offset-3">
    <div class="plan_box">
      <h3>Plan Free</h3>
      <p>No Charge
        <br>Good for evaluation
      </p>
    </div>
  </div>

  <div class="col-sm-2">
    <div class="plan_box">
      <h3>Plan Good</h3>
      <p>
        <br>Everything in free
        <br>Good plan for small businesses
      </p>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="plan_box">
      <h3>Plan Awesome</h3>
      <p>
        <br>Everything in Plan Good
        <br>Good for enterprises
      </p>
    </div>
  </div>
</div>

app/views/subscriptions/cancel_subscription.html.erb
<h1>Cancel Subscription</h1>

<p>
  <%= @message %>
</p>

app/views/subscriptions/create.html.erb
<h1>Inside Create</h1>

app/views/subscriptions/edit.html.erb
Please choose your new plan:
<br>
<%= render partial: 'plans' %>

<div class="row">
  <div class="col-sm-3 col-sm-offset-3">
    <%= form_tag "/subscriptions" do %>

  <%= collection_select :plan, :stripe_id, @plans, :stripe_id, :name, {}, { class: "form-control"} %>
  <br>
  <button type="submit" class="btn btn-primary">Update Subscription</button>

<% end %>
  </div>
</div>

app/views/subscriptions/index.html.erb
<% if @account.stripe_plan_id %>
  <% if @account.active_until > Time.now  %>
    Your subscription is valid until <%= @account.active_until %>
    <% else %>
    Your subscription expired on <%= @account.active_until %>
  <% end %>
<% else %>
  You do not have a subscription plan
<% end %>
<br><br>
<%= link_to 'Change subscription', edit_subscription_path(@account.id), { class: "btn btn-primary"} %>
<br><br>
<%= link_to 'Cancel subscription', subscriptions_cancel_subscription_path, { class: "btn btn-primary"} %>
<br><br>
<%= link_to 'Update card'        , subscriptions_update_card_path, {class: "btn btn-primary" } %>
<br><br>
<%= link_to 'New Subscription'   , new_subscription_path, {class: "btn btn-primary" } %>

app/views/subscriptions/new.html.erb
<%= render  :partial => "plans" %>

<%= render  :partial => "creditcard" %>

app/views/subscriptions/update_card.html.erb
<%= javascript_include_tag "https://js.stripe.com/v2/" %>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_tag "/subscriptions/update_card_details", id: "payment-form" do %>

      <span class="payment-errors text-danger"></span>


      <div class="form-group">
        <label for="number">Card Number</label>
        <input type="text" size="20" class="form-control" id="number" data-stripe="number"/>
      </div>

      <div class="form-group">
        <label for="cvc">CVC</label>
        <input type="text" size="4" class="form-control" id="cvc" data-stripe="cvc"/>
      </div>

      <label for="exp">Expiration (MM/YYYY)</label>

      <div class="form-group">
        <div>
          <input type="text" size="2" class="form-control exp-field" id="exp" data-stripe="exp-month"/>
          <span> / </span>
          <input type="text" size="4" class="form-control exp-field" data-stripe="exp-year"/>
        </div>
      </div>

      <button type="submit" class="btn btn-primary">Submit Payment</button>
    <% end %>

  </div>
</div>

<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_OQPwSJ6PqwdWCcOnu8EYiVG1');
  // ...
</script>