config/routes.rb
Rails.application.routes.draw do
  resources :weather_locations
  resources :weather_grids
  devise_for :users, controllers: { registrations: "registrations" , sessions: "sessions"}

resources :weather_grid

get '/subscriptions/cancel_subscription'  => 'subscriptions#cancel_subscription'
get '/subscriptions/update_card'          => 'subscriptions#update_card'
post '/subscriptions/update_card_details' => 'subscriptions#update_card_details'

resources :subscriptions

root to: "home#index"

mount StripeEvent::Engine, at: '/stripe-event' # provide a custom path

end

app/models/weather_location.rb
class WeatherLocation < ActiveRecord::Base
  belongs_to :weather_grid
end

app/controllers/weather_locations_controller.rb
class WeatherLocationsController < ApplicationController
  before_action :set_weather_location, only: [:show, :edit, :update, :destroy]

  # GET /weather_locations
  # GET /weather_locations.json
  def index
    @weather_locations = WeatherLocation.all
  end

  # GET /weather_locations/1
  # GET /weather_locations/1.json
  def show
  end

  # GET /weather_locations/new
  def new
    @weather_location = WeatherLocation.new
  end

  # GET /weather_locations/1/edit
  def edit
  end

  # POST /weather_locations
  # POST /weather_locations.json
  def create
    @weather_location = WeatherLocation.new(weather_location_params)

    respond_to do |format|
      if @weather_location.save
        format.html { redirect_to @weather_location, notice: 'Weather location was successfully created.' }
        format.json { render :show, status: :created, location: @weather_location }
      else
        format.html { render :new }
        format.json { render json: @weather_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weather_locations/1
  # PATCH/PUT /weather_locations/1.json
  def update
    respond_to do |format|
      if @weather_location.update(weather_location_params)
        format.html { redirect_to @weather_location, notice: 'Weather location was successfully updated.' }
        format.json { render :show, status: :ok, location: @weather_location }
      else
        format.html { render :edit }
        format.json { render json: @weather_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weather_locations/1
  # DELETE /weather_locations/1.json
  def destroy
    @weather_location.destroy
    respond_to do |format|
      format.html { redirect_to weather_locations_url, notice: 'Weather location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather_location
      @weather_location = WeatherLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weather_location_params
      params.require(:weather_location).permit(:weather_grid_id, :latitude, :longitude, :city)
    end
end

app/helpers/weather_locations_helper.rb
module WeatherLocationsHelper
end

app/views/weather_locations/_form.html.erb
<%= simple_form_for(@weather_location) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :weather_grid %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :city %>
  </div>



  <div class="form-actions">
    <%= f.button :submit %>
    <button type="button" class="btn btn-primary" onClick="getLatNLong()">Get Lat/Long</button>
  </div>
<% end %>

app/views/weather_locations/edit.html.erb
<h1>Editing Weather Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @weather_location %> |
<%= link_to 'Back', weather_locations_path %>

app/views/weather_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Weather Locations</h1>

<table>
  <thead>
    <tr>
      <th>Weather grid</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weather_locations.each do |weather_location| %>
      <tr>
        <td><%= weather_location.weather_grid.name %></td>
        <td><%= weather_location.latitude %></td>
        <td><%= weather_location.longitude %></td>
        <td><%= weather_location.city %></td>
        <td><%= link_to 'Show', weather_location %></td>
        <td><%= link_to 'Edit', edit_weather_location_path(weather_location) %></td>
        <td><%= link_to 'Destroy', weather_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather location', new_weather_location_path %>

app/views/weather_locations/new.html.erb
<h1>New Weather Location</h1>

<%= render 'form' %>

<%= link_to 'Back', weather_locations_path %>

app/views/weather_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weather grid:</strong>
  <%= @weather_location.weather_grid %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @weather_location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @weather_location.longitude %>
</p>

<p>
  <strong>City:</strong>
  <%= @weather_location.city %>
</p>

<%= link_to 'Edit', edit_weather_location_path(@weather_location) %> |
<%= link_to 'Back', weather_locations_path %>